# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "elixir"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "discuss"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
volumes:
  db-data:
